### ISSUE TITLE
Not found Leap.DLL

### ISSUE THREAD

**Issue by kwanggaeto** [logotype/LeapMotionAS3#43]
hi,

i making a app with leapmotion.

and an error message dialog occurs when i run the app.

the error is "Not found Leap.DLL...blah..blah"

but, leap motion is correctly work in the app.

before that,

when i debug in Flash CC, occurs some error that is

[LeapNative] Leap Motion Native Extension is not supported.
[LeapNative] If you are on Windows, add the Leap Motion software folder to your PATH.
[LeapNative] Falling back on Socket implementation.

but, leap motion is correctly work. too.

i did set the system variables and all settings along guide.

OS : windows7 64bit
IDE : Flash CC
AIR : AIRSDK13
and using ac2 version ane.

please help!! if i can't solve this error, i was kill by my boss.

**Comment by arsaln0210** [comment]
i have problem durng making leap motion app using VS_2017
error: TypeInitializationException: The type initializer for 'Leap.LeapPINVOKE' threw an exception etc.
and not found native dll file 
and not loaded dll file
im using x64 bit system but not sure about leap.dll and leapCSharp.dll 
how can  i check leap.dll and leapCSharp.dll are x64 or x86?
kndly share x64 dll file for c# VS_2017
