### ISSUE TITLE
using the latest example and setting setPolicyFlags

### ISSUE THREAD

**Issue by Fragilem17** [logotype/LeapMotionAS3#50]
Same issue as before. The moment i set Controller.POLICY_IMAGES or any other policy i constantly get connect/disconnect traces. The example with the bitmaps never shown any.

When i don't set the policy i get tracking but the number of fingers is always reporting 5 (for 1 hand) even when i make a fist. the number of hands does work.

I'm on Windows, compiling with Air 15, setting the inline and swf version command lines.
added both the leap dll's to AIR 15's bin folder.

Could it be a windows thing? are you testing on Windows?

**Comment by logotype** [comment]
Hi, no, only testing on Mac...
