### ISSUE TITLE
Can not initialize controller when launching from server.

### ISSUE THREAD

**Issue by sintro** [logotype/LeapMotionAS3#51]
I build .swf for using in KRPano plugin, and everything works fine when I launch the tour (and hence included swf plugin for Leap interaction) just by executing .swf file from my PC. But if I put it in local server (WAMP) or remote server (web-hosting), the plugin is not working. It lauch, but the only event which is called - LeapEvent.LEAPMOTION_DISCONNECTED. I checked the similar thing happens when I create new Controller with wrong IP (not default or localhost or 127.0.0.1). So I think the problem is when my SWF trying to connect to Leap Device from server, it can not connect to my computer. 
Does anyone have any minds about this problem? May be someone faced similar problem?

**Comment by logotype** [comment]
Hi, I can't compile the ANE for 64-bit on Windows, so for now it's unsupported, sorry!
