### ISSUE TITLE
Any plans to update ANE to be 64 bit

### ISSUE THREAD

**Issue by dgurney75** [logotype/LeapMotionAS3#52]
With Apple's new policy of all apps being 32 and 64 bit compatible, do you have any plans to update the ANE to support this? It would be much appreciated.

**Comment by logotype** [comment]
Hi

Yes, definitively. It's on the todo list. As soon as I can find some time to work on this, it's highest priority!

BR,
Victor

**Comment by 22ROUND** [comment]
excellent

**Comment by logotype** [comment]
Update. I'm currently working on this and have received a development pre-release of AIR from Adobe. But I'm waiting for some support since its some issues during 64-bit compilation. Hope to have this resolved soon!

**Comment by logotype** [comment]
Update. Mac ANE updated to 64-bit universal. Sorry for the delay!
