### ISSUE TITLE
MacOS-x86 not supported?

### ISSUE THREAD

**Issue by Chris-TCN** [logotype/LeapMotionAS3#53]
I always get the message "The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.leapmotion.leap.air.native.LeapNative is not supported for MacOS-x86." when I am trying to test the movie. When I go into the extracted files and change the MacOS-x86-64 to MacOS-x86 in both the xml and the folder name everything is running fine.
Problem is I can't compile it in the end, it then comes up with the same message again.

Mac OS X 10.10.3 (14D136)
Flash 2015.0 15.0.0.173
AIR 18.0.0.143

**Comment by logotype** [comment]
Hi

Currently, this ANE only works on a development build of AIR, built for 64-bit. It will be released soon by Adobe.
