### ISSUE TITLE
Is iOS and Android supported ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [logotype/LeapMotionAS3#54]
Adobe's site lists this extension as being for the following devices

iOS/Android/Windows/Mac OSX

I presume Adobe have got it wrong, as this repo only seems to contain implementations for OSX and Windows.

I don't need to use this extension, I was just reviewing what ANE's were available for which platform. So if this ANE is not for iOS or Android, perhaps you can tell Adobe (not that they are renowned for responding to any form of communication :-(   )

**Comment by logotype** [comment]
Hi

Yes, this library works on both iOS and Android. Simply include the swc in the project, and it'll work.
